apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: request-new-k8s-service
  title: Request New Kubernetes Service
  description: Create a new Kubernetes service with base manifests and overlays
  tags:
    - under-construction
    - k8s
spec:
  owner: team:devops
  type: request

  parameters:
    - title: Service Details
      required:
        - application_name
        - environment
        - team_name
        - owner
      properties:
        application_name:
          title: Application Name
          type: string
          description: Unique name of the application (e.g., my-service)
          ui:autofocus: true
        environment:
          title: Environment
          type: string
          description: Environment (e.g., stage, prod)
          default: stage
          enum:
            - stage
            - prod
        team_name:
          title: Team Name
          type: string
          description: Team name (e.g., devops)
          default: My Team
        owner:
          title: Owner
          type: string
          description: Owner (e.g., devops)
          default: Service Owner
  steps:
    - id: create-ecr
      name: Create ECR Repository
      action: aws:ecr:create
      continueOnError: true
      input:
        repositoryName: ${{ parameters.application_name }}
        tags:
          - Key: CreatedBy
            Value: DevOpsHub
          - Key: team
            Value: ${{ parameters.team_name }}
    - id: fetch-base
      name: Fetch Base Skeleton
      action: fetch:template
      input:
        url: ./skeleton/go/repository
        values:
          application_name: ${{ parameters.application_name }}
          image_repository: ${{ parameters.application_name }}
          image_tag: "init"
          ingress_host_stage: ${{ parameters.ingress_host_stage }}
          ingress_host_prod: ${{ parameters.ingress_host_prod }}
          team_name: ${{ parameters.team_name }}
          owner: ${{ parameters.owner }}
    - id: create-repo
      action: github:repo:create
      continueOnError: true
      input:
        repoUrl: github.com?owner=poptech-global-tech-pvt-ltd&repo=${{ parameters.application_name }}
        description: ${{ parameters.application_name }}
    - id: push-to-repo
      action: github:repo:push
      input:
        repoUrl: github.com?owner=poptech-global-tech-pvt-ltd&repo=${{ parameters.application_name }}
        defaultBranch: main
        sourcePath: .
    - id: fetch-k8s-template
      action: fetch:template
      input:
        url: ./skeleton/k8s
        values:
          application_name: ${{ parameters.application_name }}
          image_repository: ${{ parameters.application_name }}
          image_tag: "init"
          ingress_host_stage: ${{ parameters.ingress_host_stage }}
          ingress_host_prod: ${{ parameters.ingress_host_prod }}
          team_name: ${{ parameters.team_name }}
          owner: ${{ parameters.owner }}
        targetPath: ./${{ parameters.application_name }}/k8s
    - id: create-pr-cicd-prod
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=cicd-prod&owner=poptech-global-tech-pvt-ltd
        branchName: add-${{ parameters.application_name }}
        description: "Adding ${{ parameters.application_name }} to cicd-prod"
        title: "Add ${{ parameters.application_name }} to cicd-prod"
        commitMessage: "Adds ${{ parameters.application_name }} to cicd-prod"
        sourcePath: ./${{ parameters.application_name }}/k8s
        targetPath: ./${{ parameters.application_name }}/k8s
    - id: fetch-argo-template
      action: fetch:template
      input:
        url: ./skeleton/argocd
        values:
          application_name: ${{ parameters.application_name }}
          image_repository: ${{ parameters.application_name }}
          image_tag: "init"
          ingress_host_stage: ${{ parameters.ingress_host_stage }}
          ingress_host_prod: ${{ parameters.ingress_host_prod }}
          team_name: ${{ parameters.team_name }}
          owner: ${{ parameters.owner }}
        targetPath: ./argocdapp
    - id: create-pr-argocd
      name: Create PR for ArgoCD
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=ArgoCDApps&owner=poptech-global-tech-pvt-ltd
        branchName: add-${{ parameters.application_name }}
        description: "Adding ${{ parameters.application_name }} to argocd"
        title: "Add ${{ parameters.application_name }} to argocd"
        commitMessage: "Adds ${{ parameters.application_name }} to argocd"
        sourcePath: ./argocdapp
        targetPath: ./prod/${{ parameters.application_name }}