apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: request-pre-prod
  title: Request Pre-Prod Setup For Your Existing Service
  description: Request Pre-Prod Setup For Your Existing Service
spec:
  owner: team:infra
  type: request
  parameters:
    - title: Setup Details
      required: [RepoUrl, TeamName, Owner, serviceName]
      properties:
        RepoUrl:
          title: Repository URL
          type: string
          description: URL of the existing service repository in Github
        TeamName:
          title: Team Name
          type: string
          description: Name of the team requesting the pre-prod setup
        Owner:
          title: Owner
          type: string
          description: Owner of this setup requestA
        serviceName:
          title: Service Name
          type: string
          description: Name of the service for which pre-prod setup is requested
  steps:
    - id: fetch-k8s-files
      name: Copy K8s Files
      action: fetch:plain
      input:
        url: ${{ parameters.RepoUrl }}/tree/main/k8s
        targetPath: ./k8s-files
    - id: debug-list
      name: List Workspace Files
      action: debug:log
      input:
        message: "Files fetched from the repository"
        listWorkspace: true
    # Step 3: Create PR in ArgoCDRepo
    - id: create-pr
      name: Create Pull Request in CI/CD Repository
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=poptech-global-tech-pvt-ltd&repo=cicd-prod
        branchName: create-pre-prod-${{ parameters.serviceName }}-setup
        title: "Add ${{ parameters.serviceName }} to ArgoCD"
        description: |
          This PR adds Kubernetes manifests for ${{ parameters.serviceName }}.
          
          Source: ${{ parameters.sourceRepoUrl }}
        sourcePath: ./k8s-files
        targetPath: ./${{ parameters.serviceName }}-pre-prod

    
